export const jobTitleList = [
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Software Engineer",
  "Senior Software Engineer",
  "Junior Software Engineer",
  "Lead Developer",
  "UI/UX Designer",
  "UX Researcher",
  "Visual Designer",
  "Product Designer",
  "Interaction Designer",
  "Web Developer",
  "Mobile Developer",
  "iOS Developer",
  "Android Developer",
  "Flutter Developer",
  "React Developer",
  "Vue.js Developer",
  "Angular Developer",
  "JavaScript Developer",
  "TypeScript Developer",
  "Python Developer",
  "Java Developer",
  "C# Developer",
  "C++ Developer",
  "Rust Developer",
  "Go Developer",
  "Ruby Developer",
  "PHP Developer",
  "WordPress Developer",
  "Shopify Developer",
  "Magento Developer",
  "Drupal Developer",
  "Salesforce Developer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Cloud Engineer",
  "AWS Engineer",
  "Azure Engineer",
  "GCP Engineer",
  "Infrastructure Engineer",
  "Platform Engineer",
  "Security Engineer",
  "Cybersecurity Analyst",
  "Penetration Tester",
  "Network Security Engineer",
  "Cloud Security Engineer",
  "Application Security Engineer",
  "Blockchain Developer",
  "Smart Contract Developer",
  "AI Engineer",
  "ML Engineer",
  "Data Scientist",
  "Data Analyst",
  "Business Intelligence Analyst",
  "Big Data Engineer",
  "Data Engineer",
  "ETL Developer",
  "Database Administrator",
  "SQL Developer",
  "NoSQL Engineer",
  "MongoDB Engineer",
  "PostgreSQL Expert",
  "Firebase Developer",
  "Project Manager",
  "Product Manager",
  "Technical Product Manager",
  "Agile Coach",
  "Scrum Master",
  "Business Analyst",
  "QA Engineer",
  "Test Automation Engineer",
  "Manual QA Tester",
  "Quality Assurance Lead",
  "Performance Tester",
  "Game Developer",
  "Game Designer",
  "Game Artist",
  "Unity Developer",
  "Unreal Engine Developer",
  "AR/VR Developer",
  "3D Artist",
  "Motion Designer",
  "Animator",
  "Graphic Designer",
  "Visual Effects Artist",
  "Multimedia Designer",
  "Marketing Manager",
  "Digital Marketing Specialist",
  "SEO Specialist",
  "Content Strategist",
  "Content Writer",
  "Copywriter",
  "Email Marketing Specialist",
  "Social Media Manager",
  "Community Manager",
  "Brand Manager",
  "Growth Hacker",
  "Marketing Analyst",
  "E-commerce Manager",
  "Sales Manager",
  "Account Executive",
  "Account Manager",
  "Customer Success Manager",
  "Customer Support Specialist",
  "Tech Support Specialist",
  "Help Desk Technician",
  "IT Support Specialist",
  "IT Technician",
  "Network Administrator",
  "System Administrator",
  "IT Manager",
  "IT Director",
  "Chief Technology Officer",
  "Chief Information Officer",
  "CTO",
  "CIO",
  "Engineering Manager",
  "Technical Lead",
  "Team Lead",
  "VP of Engineering",
  "Director of Engineering",
  "Solution Architect",
  "Software Architect",
  "Enterprise Architect",
  "Cloud Architect",
  "Data Architect",
  "UX Architect",
  "Information Architect",
  "Technical Writer",
  "Documentation Specialist",
  "Instructional Designer",
  "Accessibility Specialist",
  "Compliance Officer",
  "Legal Counsel",
  "Ethical Hacker",
  "Data Privacy Officer",
  "Data Protection Officer",
  "Data Governance Specialist",
  "CRM Specialist",
  "ERP Consultant",
  "SAP Consultant",
  "Oracle Developer",
  "Linux Engineer",
  "Windows System Engineer",
  "Mac System Engineer",
  "Mobile App Tester",
  "Security Analyst",
  "Incident Responder",
  "Forensics Analyst",
  "Reverse Engineer",
  "BI Developer",
  "DWH Developer",
  "Statistics Analyst",
  "Financial Analyst",
  "Investment Analyst",
  "Actuarial Analyst",
  "Robotics Engineer",
  "Embedded Systems Engineer",
  "IoT Developer",
  "Firmware Engineer",
  "Hardware Engineer",
  "Electrical Engineer",
  "Mechanical Engineer",
  "Civil Engineer",
  "Architect (Construction)",
  "Interior Designer",
  "Urban Planner",
  "Game QA Tester",
  "Game Producer",
  "LiveOps Manager",
  "Streaming Engineer",
  "Video Editor",
  "Photographer",
  "Sound Designer",
  "Voice Over Artist",
  "Recruiter",
  "Technical Recruiter",
  "HR Manager",
  "People Operations Manager",
  "Office Manager",
  "Administrative Assistant",
  "Virtual Assistant",
  "Executive Assistant",
  "Operations Manager",
  "Logistics Coordinator",
  "Procurement Specialist",
  "Supply Chain Analyst",
  "Warehouse Manager",
  "Customer Experience Designer",
  "Design Strategist",
  "Innovation Consultant",
  "Sustainability Consultant",
  "ESG Analyst",
  "AI Prompt Engineer",
  "AI Trainer",
  "AI Ethicist",
  "Prompt Designer",
  "LLM Developer",
  "NLP Engineer",
  "Voice AI Engineer",
  "Text-to-Speech Specialist",
  "Nurse",
  "Registered Nurse",
  "Nurse Practitioner",
  "Doctor",
  "General Practitioner",
  "Surgeon",
  "Dentist",
  "Dental Hygienist",
  "Pharmacist",
  "Pharmacy Technician",
  "Radiologic Technologist",
  "Medical Assistant",
  "Physician Assistant",
  "Occupational Therapist",
  "Physical Therapist",
  "Psychologist",
  "Psychiatrist",
  "Caregiver",
  "Home Health Aide",
  "Paramedic",
  "EMT",

  "Truck Driver",
  "Delivery Driver",
  "Forklift Operator",
  "Logistics Coordinator",
  "Warehouse Worker",
  "Warehouse Manager",
  "Inventory Clerk",
  "Supply Chain Manager",
  "Shipping and Receiving Clerk",
  "Freight Broker",
  "Route Planner",
  "Dispatcher",
  "Bus Driver",
  "Taxi Driver",
  "Courier",

  "Car Salesman",
  "Retail Sales Associate",
  "Store Manager",
  "Cashier",
  "Customer Service Representative",
  "Sales Associate",
  "Sales Manager",
  "Sales Representative",
  "Merchandiser",
  "Inventory Manager",

  "Electrician",
  "Plumber",
  "HVAC Technician",
  "Carpenter",
  "Construction Worker",
  "Mason",
  "Welder",
  "Mechanic",
  "Auto Technician",
  "Machine Operator",
  "Maintenance Technician",
  "Janitor",
  "Custodian",
  "Painter",
  "Landscaper",
  "Gardener",
  "Roofer",
  "Glazier",

  "Chef",
  "Cook",
  "Line Cook",
  "Sous Chef",
  "Barista",
  "Bartender",
  "Waiter",
  "Waitress",
  "Host",
  "Hotel Receptionist",
  "Housekeeper",
  "Dishwasher",
  "Restaurant Manager",
  "Food Delivery Driver",

  "Teacher",
  "Substitute Teacher",
  "Teaching Assistant",
  "School Counselor",
  "Tutor",
  "Childcare Worker",
  "Social Worker",
  "Librarian",
  "Daycare Worker",

  "Photographer",
  "Videographer",
  "Event Planner",
  "DJ",
  "Musician",
  "Actor",
  "Voice Actor",
  "Model",
  "Writer",
  "Editor",
  "Journalist",
  "Blogger",
  "Influencer",
    "Lawyer",
  "Paralegal",
  "Legal Assistant",
  "Legal Secretary",
  "Judge",
  "Court Clerk",
  "Compliance Officer",

  // Government & Public Sector
  "Police Officer",
  "Firefighter",
  "Correctional Officer",
  "Postal Worker",
  "City Planner",
  "Tax Examiner",
  "Immigration Officer",
  "Customs Officer",
  "Public Administrator",

  // Finance & Accounting
  "Accountant",
  "Bookkeeper",
  "Auditor",
  "Financial Advisor",
  "Investment Banker",
  "Loan Officer",
  "Tax Preparer",
  "Payroll Specialist",
  "Budget Analyst",

  // Education & Academic
  "Professor",
  "Lecturer",
  "Academic Advisor",
  "Dean",
  "Principal",
  "Superintendent",
  "Curriculum Developer",
  "Special Education Teacher",
  "School Nurse",

  // Sports & Recreation
  "Fitness Trainer",
  "Personal Trainer",
  "Yoga Instructor",
  "Athletic Coach",
  "Referee",
  "Lifeguard",
  "Swimming Instructor",
  "Sports Agent",
  "Gym Manager",

  // Arts, Culture & Entertainment
  "Art Director",
  "Museum Curator",
  "Archivist",
  "Theater Director",
  "Lighting Technician",
  "Sound Technician",
  "Stagehand",
  "Makeup Artist",
  "Costume Designer",
  "Tattoo Artist",

  // Real Estate & Property
  "Real Estate Agent",
  "Real Estate Broker",
  "Property Manager",
  "Leasing Agent",
  "Appraiser",
  "Home Inspector",
  "Mortgage Broker",

  // Agriculture & Farming
  "Farmer",
  "Rancher",
  "Agricultural Technician",
  "Greenhouse Worker",
  "Crop Consultant",
  "Dairy Worker",
  "Animal Breeder",
  "Fisherman",
  "Beekeeper",

  // Manufacturing & Factory Work
  "Assembler",
  "Production Worker",
  "Factory Worker",
  "Fabricator",
  "Quality Control Inspector",
  "Machinist",
  "Tool and Die Maker",
  "Textile Worker",
  "Meat Packer",

  // Hospitality, Travel & Tourism
  "Flight Attendant",
  "Pilot",
  "Travel Agent",
  "Tour Guide",
  "Cruise Ship Worker",
  "Concierge",
  "Hotel Housekeeper",
  "Front Desk Clerk",
  "Event Coordinator",
  "Casino Dealer",

  // Clerical & Office Support
  "Receptionist",
  "Office Clerk",
  "Data Entry Clerk",
  "Administrative Coordinator",
  "File Clerk",
  "Records Manager",
  "Transcriptionist",
  "Switchboard Operator",

  // Miscellaneous & Niche
  "Dog Walker",
  "Pet Groomer",
  "Zookeeper",
  "Veterinarian",
  "Animal Shelter Worker",
  "Funeral Director",
  "Mortician",
  "Chauffeur",
  "Doorman",
  "Bellhop",
  "Park Ranger",
  "Environmental Technician",
  "Hazardous Materials Technician",
  "Interpreter",
  "Sign Language Interpreter",
  "Voice Coach",
  "Drone Operator",
  "3D Modeler",
  "Escape Room Game Master",
  "Bouncer",
  "Mystery Shopper",
  "Pastor",
  "Priest",
  "Rabbi",
  "Imam",
  "Chaplain",
  "Youth Pastor",
  "Religious Educator",

  // Security & Law Enforcement (Continued)
  "Security Guard",
  "Bailiff",
  "Private Investigator",
  "Crime Scene Investigator",
  "Detective",
  "Probation Officer",
  "Border Patrol Agent",
  "Animal Control Officer",

  // Emergency & Public Safety
  "Emergency Dispatcher",
  "Crisis Counselor",
  "Disaster Relief Coordinator",
  "Search and Rescue Technician",

  // Fashion & Beauty
  "Fashion Designer",
  "Fashion Stylist",
  "Nail Technician",
  "Hair Stylist",
  "Barber",
  "Cosmetologist",
  "Aesthetician",
  "Runway Model",
  "Beauty Advisor",

  // Alternative Medicine & Wellness
  "Massage Therapist",
  "Acupuncturist",
  "Chiropractor",
  "Holistic Health Practitioner",
  "Reiki Practitioner",
  "Herbalist",
  "Meditation Coach",
  "Nutritionist",
  "Dietitian",

  // Environmental & Green Jobs
  "Environmental Scientist",
  "Ecologist",
  "Wildlife Biologist",
  "Conservation Officer",
  "Park Warden",
  "Recycling Coordinator",
  "Sustainability Specialist",
  "Wind Turbine Technician",
  "Solar Panel Installer",

  // Education Support & Training
  "School Bus Driver",
  "Lunchroom Supervisor",
  "Crossing Guard",
  "Library Assistant",
  "Hall Monitor",
  "Adult Education Instructor",
  "ESL Teacher",
  "Driving Instructor",
  "Corporate Trainer",

  // Construction Support
  "Construction Foreman",
  "Heavy Equipment Operator",
  "Crane Operator",
  "Surveyor",
  "Demolition Worker",
  "Concrete Finisher",
  "Drywall Installer",
  "Insulation Installer",
  "Tile Setter",
  "Scaffolder",

  // Warehouse, Logistics & Manufacturing
  "Packer",
  "Sorter",
  "Materials Handler",
  "Production Line Worker",
  "CNC Operator",
  "Textile Inspector",
  "Plastic Molder",
  "Welder Helper",

  // Transportation
  "Train Conductor",
  "Locomotive Engineer",
  "Subway Operator",
  "Streetcar Operator",
  "Ship Captain",
  "Deckhand",
  "Longshoreman",
  "Air Traffic Controller",
  "Aircraft Mechanic",
  "Baggage Handler",
  "Railroad Worker",

  // Agriculture & Animals (Expanded)
  "Farm Hand",
  "Stable Hand",
  "Horse Trainer",
  "Shepherd",
  "Aquaculture Technician",
  "Agronomist",
  "Soil Scientist",
  "Irrigation Technician",
  "Slaughterhouse Worker",

  // Miscellaneous & Quirky
  "Voiceover Coach",
  "Balloon Artist",
  "Magician",
  "Stunt Performer",
  "Theme Park Attendant",
  "Carnival Worker",
  "Fortune Teller",
  "Professional Cuddler",
  "Escape Room Designer",
  "Ski Instructor",
  "Snowboard Instructor",
  "Scuba Diving Instructor",
  "Dog Trainer",
  "Pet Sitter",
  "Kennel Assistant",
  "Horse Groomer",
    "Freelance Writer",
  "Freelance Designer",
  "Uber Driver",
  "Lyft Driver",
  "Instacart Shopper",
  "TaskRabbit Worker",
  "Freelance Developer",
  "Virtual Assistant",
  "Online Tutor",
  "Remote Customer Support Agent",
  "Dropshipper",
  "E-commerce Seller",
  "Etsy Shop Owner",
  "Affiliate Marketer",
  "SEO Consultant",
  "YouTuber",
  "Streamer",
  "Podcast Host",

  // Seasonal & Tourism
  "Ski Lift Operator",
  "Camp Counselor",
  "Theme Park Ride Operator",
  "Summer Camp Director",
  "Tour Bus Driver",
  "Holiday Decorator",
  "Beach Lifeguard",
  "Resort Staff",
  "Fishing Guide",
  "Hunting Guide",
  "Surf Instructor",
  "Zipline Operator",

  // Office & Administrative (Advanced)
  "Executive Assistant",
  "Office Manager",
  "Operations Assistant",
  "Administrative Officer",
  "Scheduler",
  "Procurement Clerk",
  "Office Coordinator",
  "HR Coordinator",
  "Benefits Administrator",

  // HR & People Operations
  "HR Manager",
  "Talent Acquisition Specialist",
  "Recruiter",
  "Head of People",
  "Onboarding Specialist",
  "Learning and Development Coordinator",
  "Compensation Analyst",

  // Tech (Less Common Titles)
  "Security Analyst",
  "Penetration Tester",
  "Ethical Hacker",
  "Scrum Master",
  "Agile Coach",
  "Site Reliability Engineer",
  "Computer Systems Analyst",
  "Tech Support Specialist",
  "Firmware Engineer",
  "Embedded Systems Engineer",

  // Scientific & Lab-Based
  "Lab Technician",
  "Biomedical Engineer",
  "Geneticist",
  "Chemist",
  "Biochemist",
  "Microbiologist",
  "Forensic Scientist",
  "Toxicologist",
  "Meteorologist",

  // Publishing, Editorial & Language
  "Translator",
  "Interpreter",
  "Proofreader",
  "Copy Editor",
  "Technical Editor",
  "Grant Writer",
  "Court Reporter",
  "Speech Pathologist",

  // Event Services & Creative Ops
  "Wedding Planner",
  "Set Designer",
  "Event Photographer",
  "Lighting Designer",
  "AV Technician",
  "Stage Manager",
  "Production Assistant",
  "Venue Coordinator",

  // Food Industry (Extended)
  "Catering Manager",
  "Food Stylist",
  "Butcher",
  "Pastry Chef",
  "Baker",
  "Sommelier",
  "Wine Steward",
  "Restaurant Host",
  "Fast Food Worker",
  "Food Truck Operator",

  // Home & Domestic Services
  "House Cleaner",
  "Nanny",
  "Private Chef",
  "Laundry Attendant",
  "Personal Organizer",
  "Home Inspector",
  "Pool Technician",
  "Handyman",
  "Window Washer",

  // Real Estate & Construction Support
  "Real Estate Photographer",
  "Mortgage Processor",
  "Construction Estimator",
  "Permit Coordinator",
  "Building Inspector",
  "Property Developer",

  // Logistics & Supply Chain (More Niche)
  "Freight Forwarder",
  "Warehouse Supervisor",
  "Supply Planner",
  "Fulfillment Associate",
  "Customs Compliance Specialist",
  "Inventory Analyst",

  // Others
  "Sustainability Consultant",
  "Ethnographer",
  "UX Researcher",
  "Behavioral Therapist",
  "Voice Therapist",
  "Anthropologist",
  "Archivist",
  "Auctioneer",
  "Court Interpreter",
  "Genealogist"

];
